### ISSUE TITLE
Error with phpunit

### ISSUE THREAD

**Issue by xheisenbugx** [kenjis/codeigniter-ss-twig#1]
I'm using your package for phpunit integration with codeigniter 3.0, but i have problems run tests. 
`PHP Fatal error:  Class 'Twig_Loader_Filesystem' not found in /var/www/html/project/application/libraries/Twig.php on line 35.`
I also am using your package for secure integration of twig in codeigniter 3.0.
Any ideas?

**Edit:** I solved it adding require_once('../../vendor/autoload.php'); in Bootstrap.php, sorry but my bad english.

**Comment by kenjis** [comment]
No problem. My English is also broken. :-)
