### ISSUE TITLE
[Question] Only one display for function?

### ISSUE THREAD

**Issue by xQuByte** [kenjis/codeigniter-ss-twig#10]
Hi!
I want to display Header, content and footer. When I use:
`$this->twig->display('Header');`
Everythink works perfectly, but when i write below
`$this->twig->display('Footer');`
i can see only footer etc.

I can see only last display in function.

**Comment by kenjis** [comment]
Yes, you can call `display()` only once.
If you want to have more than one templates, you can do like this:
https://github.com/kenjis/codeigniter-tettei-apps/blob/develop/application/views/shop_tmpl_shop.twig
See Twig documentation: http://twig.sensiolabs.org/doc/templates.html#including-other-templates

Or you can get the output string with using `rendar()` method.

``` php
$output = $this->twig->render('welcome', $data);
```

**Comment by xQuByte** [comment]
Thank you for your reply.
I always use this same header and footer so in every view i use
`{% include 'include/Header.twig' %}`
`{# content #}`
`{% include 'include/Footer.twig' %}`
