### ISSUE TITLE
AddExtension

### ISSUE THREAD

**Issue by provalinf** [kenjis/codeigniter-ss-twig#14]
Hello,
How do I add extensions?
In trying, I encounter a 500 error.

Thank you

**Comment by kenjis** [comment]
How about this?

``` php
$twig = $this->twig->getTwig();
$twig->addExtension(new Your_Twig_Extension());
```

**Comment by provalinf** [comment]
Yet this is what I did, but I still get a 500 error.
Do you have a solution for me ?

Thx

**Comment by provalinf** [comment]
Ok, it's good, bug browser, sorry and thx
