### ISSUE TITLE
using another helper on codeigniter-ss-twig

### ISSUE THREAD

**Issue by vheidari** [kenjis/codeigniter-ss-twig#18]
Hi,
I want using codeigniter-ss-twig for personal project. this suport another helper of codeigniter for sample form form_input or form_password. 
by using codeigniter-ss-twig I can using all features of twig ?

**Comment by kenjis** [comment]
You can add any PHP functions. See https://github.com/kenjis/codeigniter-ss-twig#adding-your-functions.
