### ISSUE TITLE
Override another twig configs?

### ISSUE THREAD

**Issue by serialine** [kenjis/codeigniter-ss-twig#19]
Twig.php

> __construct()

```
// default config
$this->config = [
    'paths' => [VIEWPATH],
    'cache' => APPPATH . 'cache/twig',
];
```

> createTwig()

```
$twig = new \Twig_Environment($this->loader, [
    'cache'       => $this->config['cache'],
    'debug'       => $debug,
    'autoescape'  => TRUE,
]);
```

> Twig_Environment($loader, `$config_array`);

Can extend `$config_array` another twig environment options without editing Twig.php ?
I need to extend config like 'auto_reload'.

http://twig.sensiolabs.org/doc/api.html#environment-options

**Comment by kenjis** [comment]
@serialine Now you can override any config.
https://github.com/kenjis/codeigniter-ss-twig/commit/1202edb3e1a2a677e56c79b98893bfea0acf74d2

Would you please try the latest dev-master?

**Comment by serialine** [comment]
it's works well, thank you :)
