### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by dexterns88** [kenjis/codeigniter-ss-twig#3]
Can you add configuration for twig in codeigniter.

**Comment by kenjis** [comment]
What configuration do you need?

**Comment by kenjis** [comment]
@dexterns88 What configuration do you need?

**Comment by dexterns88** [comment]
I need to extend twig function with some php function and maybe to add configuration for turn off/on cache and patch to cache folder and similar.

**Comment by kenjis** [comment]
Now you can configure `cache` option: https://github.com/kenjis/codeigniter-ss-twig#loading-twig-library

If you want to add twig function, you can get `Twig_Environment` instance using `$this->twig->getTwig()`.

``` php
$twig = $this->twig->getTwig();
$twig->addFunction($function);
```

**Comment by kenjis** [comment]
If you have still any suggestions, please feel free to create a new issue.
