### ISSUE TITLE
Delayed updates on views regarding changes made to variables on controllers.

### ISSUE THREAD

**Issue by unknownbreakdown** [kenjis/codeigniter-ss-twig#33]
Hello.  I've installed codeigniter-ss-twig, under Bitnami LAMP Stack, following the instructions using composer and also manually, and in both cases when changes are made to variables on controllers, there's a delay (after some page refreshes) to get them updated when the view is rendered on the browser.  This issue is only regarding variables.  Changes made to static content on the view gets updated immediately when the page refreshes.  I've tried even setting up the cache to false on the libraries/Twig class.

It was a default Bitnami Lamp Stack configuration issue.  I edited the php.ini file and changed option opcache.enable from 1 to 0.  I couldn't imagine Bitnami LAMP Stack wasn't properly setup for development environments.

Great work with the codeigniter-ss-twig, Kenjis.

**Comment by kenjis** [comment]
@unknownbreakdown Thanks!
