### ISSUE TITLE
Using with Twig 2.x

### ISSUE THREAD

**Issue by yahyaerturan** [kenjis/codeigniter-ss-twig#34]
In Readme, it says we can check out with Twig 2.x but when I do it, it gives me the following error:

```php

Fatal error: Class 'Twig_Loader_Filesystem' not found in 
/.../Code/myproject/application/libraries/Twig.php on line 117
```
Do we need to something else for Twig 2.x. By the way I am using Composer to install Twig and other packages.

**Comment by kenjis** [comment]
You need autoloader. But if you install via Composer, you can use Composer's autoloader.
Do you set up Composer autoloader for CodeIgniter?
https://www.codeigniter.com/user_guide/general/autoloader.html

**Comment by kenjis** [comment]
If you have still the problem, feel free to reopen.
