### ISSUE TITLE
how to setting twig with hmvc in codeigniter, please?

### ISSUE THREAD

**Issue by quanglong2907** [kenjis/codeigniter-ss-twig#37]
An uncaught Exception was encountered
Type: Twig_Error_Loader

Message: Unable to find template "test.twig" (looked into: E:\xampp\htdocs\ci_blog2\application\views).

Filename: E:\xampp\htdocs\ci_blog2\vendor\twig\twig\lib\Twig\Loader\Filesystem.php

Line Number: 232

**Comment by kenjis** [comment]
See <https://github.com/kenjis/codeigniter-ss-twig/pull/13#issuecomment-207315399>.
