### ISSUE TITLE
Right way to add function like form_open() without | raw

### ISSUE THREAD

**Issue by wichaksono** [kenjis/codeigniter-ss-twig#40]
![image](https://user-images.githubusercontent.com/11472981/37013265-9bc74c7e-212b-11e8-8242-f8602388a09f.png)

i try to add form_open_multipart(). so far i can added but i must use {{ form_open_multipart()|raw }}
i wanna use without "raw"

**Comment by kenjis** [comment]
@wichaksono 
I don't know why you must use `raw'.

I use `config/twig.php`:

```php
$config['functions_safe'] = [
    'form_open_multipart',
];
```

And I can use `{{ form_open_multipart() }}`.

**Comment by wichaksono** [comment]
Oh Thanks i can do this now
