### ISSUE TITLE
How to use session flashdata function

### ISSUE THREAD

**Issue by alcanardanangelo** [kenjis/codeigniter-ss-twig#42]
Hi Kenji,

How can I use the `$this->session->flashdata()` in my view?

If I set the flashdata in my controller like this:
```
$this->session->set_flashdata('success', 'Test message');
redirect('/', 'refresh');
```

How can I call it on my view?

Thanks!

**Comment by dzakiafif** [comment]
just like this in your controller : 
`$data['message'] = $this->session->flashdata('success');`
`$this->twig->display('(your-view)',$data);`
and then in your view : 
`{% if message %}<div class="alert">{{ message }}</div>{% endif %}`
