### ISSUE TITLE
Using "true" as the default strategy is deprecated since version 1.21. Use "html" instead.

### ISSUE THREAD

**Issue by rostamiani** [kenjis/codeigniter-ss-twig#45]
Error logged

> Using "true" as the default strategy is deprecated since version 1.21. Use "html" instead.

On Escaper.php 58

Just commented "'autoescape' => TRUE," and there is no errors anymore.

**Comment by kenjis** [comment]
@rostamiani Thank you!

**Comment by kenjis** [comment]
@rostamiani I've just released v0.3.0.
