### ISSUE TITLE
Session flashdata

### ISSUE THREAD

**Issue by florentvdry** [kenjis/codeigniter-ss-twig#47]
How can i do this, with this twig template engine please ?

      <?php if($this->session->flashdata('category_created')): ?>
        <?php echo '<p class="alert alert-success">'.$this->session->flashdata('category_created').'</p>'; ?>
      <?php endif; ?>

**Comment by shayhurley** [comment]
Something like this should work:

```
{% if session.flashdata.category_created is not empty %}
    <p class="alert alert-success">{{ session.flashdata.category_created }}</p>
{% endif %}
```
