### ISSUE TITLE
Add function in twig

### ISSUE THREAD

**Issue by ArmandArthur** [kenjis/codeigniter-ss-twig#48]
Hello,

i did : `        $config = [
            'functions' => ['can'],
        ];
        $this->load->library('twig', $config);` in my parent controller

and i try to use the method of helper about: https://github.com/firoz-ahmad-likhon/codeigniter-role-base-access-control

Without success....

do you have an idea?

**Comment by ArmandArthur** [comment]
Help me please !?

**Comment by kenjis** [comment]
If you have still the problem, feel free to reopen.
