### ISSUE TITLE
Support constant

### ISSUE THREAD

**Issue by provalinf** [kenjis/codeigniter-ss-twig#5]
Hi Kenjis,
Thank you for your very good plugin, after having tested many, it is the only one that meets my needs and works perfectly.
But how can I add the addconstant (addGlobal()) support, if I write in my controller : `$this->twig->addGlobal ('', '')` , method is not defined.

I tried to add this in your extension :

``` php
    public function addGlobal($name, $value)
    {
        $this->createTwig();
        return $this->twig->addGlobal($name, $value);
    }
```

without success (I think the problem is that the object is redefined as "render" is called, but you know that better than me ^^)

Could you add this feature?
Thank you and sorry again for my translation

**Comment by kenjis** [comment]
Do you use the leatest `Twig.php`?

> I think the problem is that the object is redefined as "render" is called

I fixed the problem some days ago.

**Comment by provalinf** [comment]
I edit a message telling you that it worked, and that this was therefore a feature proposal to add, but you edit afterwards ^^.
It is functional for me, I just made a mistake.

**Comment by kenjis** [comment]
Okay, I will consider. Thank you for your proposal.

**Comment by kenjis** [comment]
I added: https://github.com/kenjis/codeigniter-ss-twig/blob/master/libraries/Twig.php#L99

**Comment by provalinf** [comment]
Superb, thank you for your rapidity.
