### ISSUE TITLE
translation with twig and ci

### ISSUE THREAD

**Issue by JcDecour** [kenjis/codeigniter-ss-twig#51]
Hello kenjis

I recently installed your twig module on a project code igniter 3, it work very properly

However, I must now translate on this project.

is it possible or not?

I can not seem to recover my translation in my views

thank you in advance

**Comment by kenjis** [comment]
What do you mean by translate?
What do you want to do exactly?

**Comment by kenjis** [comment]
If you have still the problem, feel free to reopen.
