### ISSUE TITLE
support for the new version ci4

### ISSUE THREAD

**Issue by kgrzelak** [kenjis/codeigniter-ss-twig#52]
Will there be CI-4 support?

**Comment by mvolotov** [comment]
I ported this library under CI4 for myself. There is nothing complicated about it. To work, just change a couple of lines in the file. Here is an [example ](https://github.com/AsteriaGamer/codeigniter-ss-twig/commit/b1b0f09e081a83656d2de0359eebd92bddab083d)

To use, just plug in the library.
```
<?php namespace App\Controllers;

use App\Controllers\BaseController;
use App\Libraries\Twig;
class Main extends BaseController
{
    public function index()
    {
        $data = [
                 'title' => 'MainPage',
        ];
        $twig = new Twig();
        $twig->display('main', $data);
    }
}
```

**Comment by kenjis** [comment]
This is very early development version:
https://github.com/kenjis/codeigniter-ss-twig/tree/4.x
Comments are welcome.

**Comment by kenjis** [comment]
@kgrzelak @AsteriaGamer If you have any requests or issues, feel free to create a new issue or a PR.
