### ISSUE TITLE
Class 'Twig_Loader_Filesystem' not found error

### ISSUE THREAD

**Issue by Ajax30** [kenjis/codeigniter-ss-twig#53]
In a CodeIgniter 3.1.8 application, I get the error `Class 'Twig_Loader_Filesystem' not found` after running `php vendor/kenjis/codeigniter-ss-twig/install.php`.

**Comment by kenjis** [comment]
@Ajax30 Would you please show me the full error message?

**Comment by kenjis** [comment]
If you have still the problem, feel free to reopen.
