### ISSUE TITLE
Truncate filter does not work

### ISSUE THREAD

**Issue by Ajax30** [kenjis/codeigniter-ss-twig#54]
Using `{{post.content|truncate(100)}}` or `{{post.content|raw|truncate(100)}}` (with Twig 1.44.1) does not work. 
The application throws an `Unknown "truncate" filter` error message.

**Comment by kenjis** [comment]
@Ajax30 https://twig.symfony.com/doc/1.x/ There is no `truncate` filter.

**Comment by kenjis** [comment]
If you have still the problem, feel free to reopen.
