### ISSUE TITLE
way to pass more config to twig environment

### ISSUE THREAD

**Issue by agung-wete** [kenjis/codeigniter-ss-twig#57]
available right now:
https://github.com/kenjis/codeigniter-ss-twig/blob/a0844631028429782bf36ef1538df3bac8fd7dbd/src/CI4Twig/Twig.php#L93-L97

Doc: https://twig.symfony.com/doc/3.x/api.html#environment-options

**Comment by kenjis** [comment]
@agung-wete What do you mean? What is the exact your problem?

**Comment by agung-wete** [comment]
I'am sorry, my bad.
