### ISSUE TITLE
Memory leak in development mode if twig syntax incorrect

### ISSUE THREAD

**Issue by gixxy22** [kenjis/codeigniter-ss-twig#63]
Sometimes, if the Twig syntax is incorrect and youre in development mode, CI error output will fail on a memory exception.

![image](https://user-images.githubusercontent.com/45268517/226108808-592c64ea-a5a5-47bf-bc04-617472a0d4c7.png)

**Comment by kenjis** [comment]
It seems your issue is not because of the library.
And your report does not provide information to debug.

If Twig has memory leak, I recommend you report the bug to the Twig repository.
