### ISSUE TITLE
Using official filters from Twig

### ISSUE THREAD

**Issue by SilkeKohl** [kenjis/codeigniter-ss-twig#70]
How to use the official filters from Twig?
I'm trying to use [markdown_to_html](https://twig.symfony.com/doc/3.x/filters/markdown_to_html.html).

- It is installed using Composer (`composer require twig/markdown-extra`)

- I tried adding it to the configuration `
$config = [
'filters' => ['markdown_to_html']
]
`

- I also tried to add:
`use Twig\Extra\Markdown\DefaultMarkdown;
use Twig\Extra\Markdown\MarkdownRuntime;
use Twig\RuntimeLoader\RuntimeLoaderInterface;`

Is this generally supported by codeigniter-ss-twig?

**Comment by kenjis** [comment]
See https://github.com/kenjis/ci4-twig-sample/blob/main/app/Controllers/Markdown_sample.php

**Comment by SilkeKohl** [comment]
Thank you! It is working properly.
