### ISSUE TITLE
How to have multi theme option in this?

### ISSUE THREAD

**Issue by haider-pw** [kenjis/codeigniter-ss-twig#9]
How to have multi theme option using twig and codeigniter?

**Comment by kenjis** [comment]
What is _theme option_?

**Comment by kenjis** [comment]
If you mean grouping templates and assets, as far as I know, Twig has no such functionality.
So codeigniter-ss-twig also has no such functionality.

You can implement such system by yourself.
Or see https://github.com/davidsosavaldes/Attire. This is another Twig implementation for Codeigniter.
It might be what you seek.

**Comment by kenjis** [comment]
@pakistanihaider Any feedback?
